export const styles = {
  container: {
    position: 'relative',
    width: '100%',
    height: '100vh',
    fontFamily: 'system-ui, sans-serif',
  },
  controlBar: {
    position: 'absolute',
    top: 16,
    left: 16,
    right: 16,
    display: 'flex',
    gap: 16,
    zIndex: 10,
    flexWrap: 'wrap',
  },
  card: {
    background: '#fff',
    borderRadius: 8,
    boxShadow: '0 2px 6px rgba(0,0,0,0.12)',
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '8px 12px',
  },
  searchInput: {
    flex: 1,
    border: 'none',
    outline: 'none',
    fontSize: 14,
    minWidth: 0,
  },
  select: {
    border: 'none',
    outline: 'none',
    fontSize: 14,
    background: 'transparent',
  },
  addBtn: {
    position: 'absolute',
    bottom: 32,
    right: 32,
    background: '#22C55E',
    borderRadius: '50%',
    padding: 16,
    color: '#fff',
    boxShadow: '0 4px 8px rgba(0,0,0,0.15)',
    border: 'none',
    cursor: 'pointer',
    transition: 'transform 0.15s ease',
  },
  legend: {
    position: 'absolute',
    bottom: 32,
    left: 32,
    background: '#fff',
    borderRadius: 8,
    boxShadow: '0 2px 6px rgba(0,0,0,0.12)',
    padding: 16,
    fontSize: 12,
    lineHeight: 1.4,
  },
  legendRow: { display: 'flex', alignItems: 'center', gap: 8 },
  overlayBg: {
    position: 'absolute',
    inset: 0,
    background: 'rgba(0,0,0,0.5)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 20,
  },
  formCard: {
    background: '#fff',
    borderRadius: 8,
    boxShadow: '0 4px 10px rgba(0,0,0,0.2)',
    padding: 24,
    width: '100%',
    maxWidth: 420,
    maxHeight: '90vh',
    overflowY: 'auto',
  },
  formRow: { display: 'flex', flexDirection: 'column', gap: 4 },
  label: { fontSize: 13, fontWeight: 600 },
  input: {
    border: '1px solid #d1d5db',
    borderRadius: 6,
    padding: '6px 10px',
    fontSize: 14,
    outline: 'none',
  },
  textarea: {
    border: '1px solid #d1d5db',
    borderRadius: 6,
    padding: '6px 10px',
    fontSize: 14,
    outline: 'none',
    resize: 'vertical',
  },
  formBtns: { display: 'flex', gap: 12, marginTop: 12 },
  stats: {
    position: 'absolute',
    top: 100,
    right: 16,
    background: '#fff',
    borderRadius: 8,
    boxShadow: '0 2px 6px rgba(0,0,0,0.12)',
    padding: 16,
    fontSize: 12,
    zIndex: 10,
  },
};

/* funkcje zależne od stanu  */
export const upcomingBtnStyle = (active) => ({
  background: active ? '#FFEDD5' : '#fff',
  border: active ? '1px solid #FDBA74' : '1px solid #eee',
  borderRadius: 8,
  boxShadow: '0 2px 6px rgba(0,0,0,0.12)',
  padding: '8px 12px',
  display: 'flex',
  alignItems: 'center',
  gap: 8,
  cursor: 'pointer',
});

export const solidBtnStyle = (bg, color = '#fff') => ({
  flex: 1,
  background: bg,
  color,
  border: 'none',
  borderRadius: 6,
  padding: '8px 0',
  fontSize: 14,
  cursor: 'pointer',
});
