// Mock data for demo mode - sample clients, devices, services

// Helper to generate dates
const today = new Date();
const addDays = (days) => {
  const date = new Date(today);
  date.setDate(date.getDate() + days);
  return date.toISOString().split('T')[0];
};

const subtractDays = (days) => {
  const date = new Date(today);
  date.setDate(date.getDate() - days);
  return date.toISOString().split('T')[0];
};

// Sample clients with devices
export const mockClients = [
  {
    id: 1,
    name: 'Jan Kowalski',
    firstName: 'Jan',
    lastName: 'Kowalski',
    imie: 'Jan',
    nazwisko: 'Kowalski',
    phone: '+48 500 100 200',
    telefon: '+48 500 100 200',
    devices: [
      {
        id: 1,
        deviceId: 1,
        clientId: 1,
        clientName: 'Jan Kowalski',
        address: 'ul. Kwiatowa 15, 00-001 Warszawa',
        position: { lat: 52.2297, lng: 21.0122 },
        deviceType: 'Pompa ciepła',
        typUrzadzenia: 'Pompa ciepła',
        deviceName: 'Viessmann Vitocal 200-S',
        nazwaUrzadzenia: 'Viessmann Vitocal 200-S',
        installationDate: '2022-03-15',
        nextInspectionDate: addDays(14),
        notes: 'Pompa ciepła powietrze-woda, moc 10kW',
        serviceConfirmed: false,
        ulica: 'ul. Kwiatowa',
        nrDomu: '15',
        nrLokalu: null,
        kodPocztowy: '00-001',
        miejscowosc: 'Warszawa',
        latitude: 52.2297,
        longitude: 21.0122,
      }
    ]
  },
  {
    id: 2,
    name: 'Anna Nowak',
    firstName: 'Anna',
    lastName: 'Nowak',
    imie: 'Anna',
    nazwisko: 'Nowak',
    phone: '+48 501 200 300',
    telefon: '+48 501 200 300',
    devices: [
      {
        id: 2,
        deviceId: 2,
        clientId: 2,
        clientName: 'Anna Nowak',
        address: 'ul. Słoneczna 8/12, 02-100 Warszawa',
        position: { lat: 52.2150, lng: 21.0200 },
        deviceType: 'Kocioł gazowy',
        typUrzadzenia: 'Kocioł gazowy',
        deviceName: 'Junkers Cerapur',
        nazwaUrzadzenia: 'Junkers Cerapur',
        installationDate: '2021-06-20',
        nextInspectionDate: addDays(7),
        notes: 'Kocioł kondensacyjny 24kW',
        serviceConfirmed: true,
        serviceConfirmedAt: subtractDays(5),
        ulica: 'ul. Słoneczna',
        nrDomu: '8',
        nrLokalu: '12',
        kodPocztowy: '02-100',
        miejscowosc: 'Warszawa',
        latitude: 52.2150,
        longitude: 21.0200,
      }
    ]
  },
  {
    id: 3,
    name: 'Piotr Wiśniewski',
    firstName: 'Piotr',
    lastName: 'Wiśniewski',
    imie: 'Piotr',
    nazwisko: 'Wiśniewski',
    phone: '+48 502 300 400',
    telefon: '+48 502 300 400',
    devices: [
      {
        id: 3,
        deviceId: 3,
        clientId: 3,
        clientName: 'Piotr Wiśniewski',
        address: 'ul. Leśna 22, 03-200 Warszawa',
        position: { lat: 52.2400, lng: 21.0300 },
        deviceType: 'Klimatyzator',
        typUrzadzenia: 'Klimatyzator',
        deviceName: 'Daikin FTXM35',
        nazwaUrzadzenia: 'Daikin FTXM35',
        installationDate: '2023-05-10',
        nextInspectionDate: addDays(30),
        notes: 'Klimatyzator split 3.5kW',
        serviceConfirmed: false,
        ulica: 'ul. Leśna',
        nrDomu: '22',
        nrLokalu: null,
        kodPocztowy: '03-200',
        miejscowosc: 'Warszawa',
        latitude: 52.2400,
        longitude: 21.0300,
      },
      {
        id: 4,
        deviceId: 4,
        clientId: 3,
        clientName: 'Piotr Wiśniewski',
        address: 'ul. Leśna 22, 03-200 Warszawa',
        position: { lat: 52.2400, lng: 21.0300 },
        deviceType: 'Pompa ciepła',
        typUrzadzenia: 'Pompa ciepła',
        deviceName: 'Bosch Compress 7000i',
        nazwaUrzadzenia: 'Bosch Compress 7000i',
        installationDate: '2022-11-05',
        nextInspectionDate: subtractDays(3), // overdue
        notes: 'Pompa ciepła gruntowa',
        serviceConfirmed: false,
        ulica: 'ul. Leśna',
        nrDomu: '22',
        nrLokalu: null,
        kodPocztowy: '03-200',
        miejscowosc: 'Warszawa',
        latitude: 52.2400,
        longitude: 21.0300,
      }
    ]
  },
  {
    id: 4,
    name: 'Maria Zielińska',
    firstName: 'Maria',
    lastName: 'Zielińska',
    imie: 'Maria',
    nazwisko: 'Zielińska',
    phone: '+48 503 400 500',
    telefon: '+48 503 400 500',
    devices: [
      {
        id: 5,
        deviceId: 5,
        clientId: 4,
        clientName: 'Maria Zielińska',
        address: 'ul. Parkowa 5, 04-300 Warszawa',
        position: { lat: 52.2100, lng: 21.0500 },
        deviceType: 'Kocioł gazowy',
        typUrzadzenia: 'Kocioł gazowy',
        deviceName: 'Vaillant ecoTEC plus',
        nazwaUrzadzenia: 'Vaillant ecoTEC plus',
        installationDate: '2020-09-12',
        nextInspectionDate: addDays(21),
        notes: 'Kocioł kondensacyjny dwufunkcyjny',
        serviceConfirmed: false,
        ulica: 'ul. Parkowa',
        nrDomu: '5',
        nrLokalu: null,
        kodPocztowy: '04-300',
        miejscowosc: 'Warszawa',
        latitude: 52.2100,
        longitude: 21.0500,
      }
    ]
  },
  {
    id: 5,
    name: 'Tomasz Lewandowski',
    firstName: 'Tomasz',
    lastName: 'Lewandowski',
    imie: 'Tomasz',
    nazwisko: 'Lewandowski',
    phone: '+48 504 500 600',
    telefon: '+48 504 500 600',
    devices: [
      {
        id: 6,
        deviceId: 6,
        clientId: 5,
        clientName: 'Tomasz Lewandowski',
        address: 'ul. Ogrodowa 33, 05-400 Otwock',
        position: { lat: 52.1050, lng: 21.2600 },
        deviceType: 'Pompa ciepła',
        typUrzadzenia: 'Pompa ciepła',
        deviceName: 'Panasonic Aquarea',
        nazwaUrzadzenia: 'Panasonic Aquarea',
        installationDate: '2023-01-20',
        nextInspectionDate: addDays(45),
        notes: 'Pompa ciepła powietrze-woda T-CAP',
        serviceConfirmed: false,
        ulica: 'ul. Ogrodowa',
        nrDomu: '33',
        nrLokalu: null,
        kodPocztowy: '05-400',
        miejscowosc: 'Otwock',
        latitude: 52.1050,
        longitude: 21.2600,
      }
    ]
  },
  {
    id: 6,
    name: 'Katarzyna Dąbrowska',
    firstName: 'Katarzyna',
    lastName: 'Dąbrowska',
    imie: 'Katarzyna',
    nazwisko: 'Dąbrowska',
    phone: '+48 505 600 700',
    telefon: '+48 505 600 700',
    devices: [
      {
        id: 7,
        deviceId: 7,
        clientId: 6,
        clientName: 'Katarzyna Dąbrowska',
        address: 'ul. Wiosenna 10, 01-500 Warszawa',
        position: { lat: 52.2500, lng: 20.9800 },
        deviceType: 'Klimatyzator',
        typUrzadzenia: 'Klimatyzator',
        deviceName: 'Mitsubishi MSZ-LN35',
        nazwaUrzadzenia: 'Mitsubishi MSZ-LN35',
        installationDate: '2022-07-15',
        nextInspectionDate: subtractDays(10), // overdue
        notes: 'Klimatyzator premium z oczyszczaczem',
        serviceConfirmed: false,
        ulica: 'ul. Wiosenna',
        nrDomu: '10',
        nrLokalu: null,
        kodPocztowy: '01-500',
        miejscowosc: 'Warszawa',
        latitude: 52.2500,
        longitude: 20.9800,
      }
    ]
  },
  {
    id: 7,
    name: 'Michał Szymański',
    firstName: 'Michał',
    lastName: 'Szymański',
    imie: 'Michał',
    nazwisko: 'Szymański',
    phone: '+48 506 700 800',
    telefon: '+48 506 700 800',
    devices: [
      {
        id: 8,
        deviceId: 8,
        clientId: 7,
        clientName: 'Michał Szymański',
        address: 'ul. Cicha 7, 02-600 Warszawa',
        position: { lat: 52.1900, lng: 21.0000 },
        deviceType: 'Kocioł olejowy',
        typUrzadzenia: 'Kocioł olejowy',
        deviceName: 'Buderus Logano G125',
        nazwaUrzadzenia: 'Buderus Logano G125',
        installationDate: '2019-10-08',
        nextInspectionDate: addDays(60),
        notes: 'Kocioł olejowy niskotemperaturowy',
        serviceConfirmed: false,
        ulica: 'ul. Cicha',
        nrDomu: '7',
        nrLokalu: null,
        kodPocztowy: '02-600',
        miejscowosc: 'Warszawa',
        latitude: 52.1900,
        longitude: 21.0000,
      }
    ]
  },
  {
    id: 8,
    name: 'Agnieszka Woźniak',
    firstName: 'Agnieszka',
    lastName: 'Woźniak',
    imie: 'Agnieszka',
    nazwisko: 'Woźniak',
    phone: '+48 507 800 900',
    telefon: '+48 507 800 900',
    devices: [
      {
        id: 9,
        deviceId: 9,
        clientId: 8,
        clientName: 'Agnieszka Woźniak',
        address: 'ul. Długa 45/2, 03-700 Warszawa',
        position: { lat: 52.2600, lng: 21.0400 },
        deviceType: 'Pompa ciepła',
        typUrzadzenia: 'Pompa ciepła',
        deviceName: 'Nibe F2120',
        nazwaUrzadzenia: 'Nibe F2120',
        installationDate: '2021-12-01',
        nextInspectionDate: addDays(5),
        notes: 'Pompa ciepła powietrze-woda, inwerter',
        serviceConfirmed: true,
        serviceConfirmedAt: subtractDays(2),
        ulica: 'ul. Długa',
        nrDomu: '45',
        nrLokalu: '2',
        kodPocztowy: '03-700',
        miejscowosc: 'Warszawa',
        latitude: 52.2600,
        longitude: 21.0400,
      }
    ]
  }
];

// Extract all devices from clients for map view
export const mockDevices = mockClients.flatMap(client =>
  client.devices.map(device => ({
    ...device,
    id: client.id,
    name: client.name,
    imie: client.firstName,
    nazwisko: client.lastName,
    telefon: client.phone,
    phone: client.phone,
  }))
);

// Sample services for calendar
export const mockServices = [
  {
    id: 1,
    googleEventId: 'demo-event-1',
    title: 'Serwis: Jan Kowalski - Pompa ciepła',
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 2, 9, 0),
    end: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 2, 11, 0),
    location: 'ul. Kwiatowa 15, 00-001 Warszawa',
    description: 'Przegląd okresowy pompy ciepła',
    status: 'SCHEDULED',
    clientId: 1,
    deviceId: 1,
    clientName: 'Jan Kowalski',
    clientPhone: '+48 500 100 200',
    deviceName: 'Viessmann Vitocal 200-S',
    deviceType: 'Pompa ciepła',
    serviceType: 'Przegląd okresowy',
  },
  {
    id: 2,
    googleEventId: 'demo-event-2',
    title: 'Serwis: Anna Nowak - Kocioł gazowy',
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 3, 13, 0),
    end: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 3, 14, 30),
    location: 'ul. Słoneczna 8/12, 02-100 Warszawa',
    description: 'Konserwacja kotła gazowego',
    status: 'SCHEDULED',
    clientId: 2,
    deviceId: 2,
    clientName: 'Anna Nowak',
    clientPhone: '+48 501 200 300',
    deviceName: 'Junkers Cerapur',
    deviceType: 'Kocioł gazowy',
    serviceType: 'Konserwacja',
  },
  {
    id: 3,
    googleEventId: 'demo-event-3',
    title: 'Serwis: Piotr Wiśniewski - Klimatyzator',
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 5, 10, 0),
    end: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 5, 11, 30),
    location: 'ul. Leśna 22, 03-200 Warszawa',
    description: 'Czyszczenie i serwis klimatyzatora',
    status: 'SCHEDULED',
    clientId: 3,
    deviceId: 3,
    clientName: 'Piotr Wiśniewski',
    clientPhone: '+48 502 300 400',
    deviceName: 'Daikin FTXM35',
    deviceType: 'Klimatyzator',
    serviceType: 'Konserwacja',
  },
  {
    id: 4,
    googleEventId: 'demo-event-4',
    title: 'Serwis: Maria Zielińska - Kocioł gazowy',
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 7, 8, 0),
    end: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 7, 10, 0),
    location: 'ul. Parkowa 5, 04-300 Warszawa',
    description: 'Przegląd roczny kotła gazowego',
    status: 'SCHEDULED',
    clientId: 4,
    deviceId: 5,
    clientName: 'Maria Zielińska',
    clientPhone: '+48 503 400 500',
    deviceName: 'Vaillant ecoTEC plus',
    deviceType: 'Kocioł gazowy',
    serviceType: 'Przegląd okresowy',
  },
  {
    id: 5,
    googleEventId: 'demo-event-5',
    title: 'Serwis: Agnieszka Woźniak - Pompa ciepła',
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 1, 14, 0),
    end: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 1, 16, 0),
    location: 'ul. Długa 45/2, 03-700 Warszawa',
    description: 'Przegląd okresowy pompy ciepła',
    status: 'SCHEDULED',
    clientId: 8,
    deviceId: 9,
    clientName: 'Agnieszka Woźniak',
    clientPhone: '+48 507 800 900',
    deviceName: 'Nibe F2120',
    deviceType: 'Pompa ciepła',
    serviceType: 'Przegląd okresowy',
  },
  {
    id: 6,
    googleEventId: 'demo-event-6',
    title: 'Serwis: Katarzyna Dąbrowska - Klimatyzator',
    start: new Date(today.getFullYear(), today.getMonth(), today.getDate(), 11, 0),
    end: new Date(today.getFullYear(), today.getMonth(), today.getDate(), 12, 30),
    location: 'ul. Wiosenna 10, 01-500 Warszawa',
    description: 'Naprawa klimatyzatora - wyciek freonu',
    status: 'SCHEDULED',
    clientId: 6,
    deviceId: 7,
    clientName: 'Katarzyna Dąbrowska',
    clientPhone: '+48 505 600 700',
    deviceName: 'Mitsubishi MSZ-LN35',
    deviceType: 'Klimatyzator',
    serviceType: 'Naprawa',
  }
];

// Custom clients - service requests from public page (for custom clients page)
export const mockCustomClients = [
  {
    id: 101,
    imie: 'Robert',
    nazwisko: 'Malinowski',
    telefon: '+48 512 345 678',
    contacted: false,
    createdAt: subtractDays(1),
    devices: [
      {
        id: 201,
        typUrzadzenia: 'Pompa ciepła',
        nazwaUrzadzenia: 'Viessmann Vitocal 300-G',
        dataInstalacji: '2021-04-15',
        terminPrzegladu: subtractDays(30),
        notatka: 'Proszę o kontakt w sprawie przeglądu. Urządzenie działa głośniej niż zwykle.',
        ulica: 'ul. Brzozowa',
        nrDomu: '12',
        nrLokalu: null,
        kodPocztowy: '02-450',
        miejscowosc: 'Warszawa',
        latitude: 52.1980,
        longitude: 21.0150,
      }
    ]
  },
  {
    id: 102,
    imie: 'Ewa',
    nazwisko: 'Pawlak',
    telefon: '+48 601 234 567',
    contacted: false,
    createdAt: subtractDays(2),
    devices: [
      {
        id: 202,
        typUrzadzenia: 'Kocioł gazowy',
        nazwaUrzadzenia: 'Viessmann Vitodens 200-W',
        dataInstalacji: '2020-09-20',
        terminPrzegladu: subtractDays(15),
        notatka: 'Kocioł wymaga corocznego przeglądu. Proszę o ustalenie terminu.',
        ulica: 'ul. Lipowa',
        nrDomu: '45',
        nrLokalu: '3',
        kodPocztowy: '03-100',
        miejscowosc: 'Warszawa',
        latitude: 52.2550,
        longitude: 21.0320,
      }
    ]
  },
  {
    id: 103,
    imie: 'Krzysztof',
    nazwisko: 'Nowicki',
    telefon: '+48 789 012 345',
    contacted: true,
    contactedAt: subtractDays(1),
    createdAt: subtractDays(3),
    devices: [
      {
        id: 203,
        typUrzadzenia: 'Klimatyzator',
        nazwaUrzadzenia: 'LG Artcool Gallery',
        dataInstalacji: '2023-06-10',
        terminPrzegladu: addDays(60),
        notatka: 'Klimatyzator nie chłodzi wystarczająco. Może wymaga uzupełnienia czynnika.',
        ulica: 'ul. Akacjowa',
        nrDomu: '8',
        nrLokalu: null,
        kodPocztowy: '01-200',
        miejscowosc: 'Warszawa',
        latitude: 52.2420,
        longitude: 20.9800,
      }
    ]
  },
  {
    id: 104,
    imie: 'Magdalena',
    nazwisko: 'Kaczmarek',
    telefon: '+48 660 111 222',
    contacted: false,
    createdAt: subtractDays(0),
    devices: [
      {
        id: 204,
        typUrzadzenia: 'Pompa ciepła',
        nazwaUrzadzenia: 'Mitsubishi Ecodan',
        dataInstalacji: '2022-11-01',
        terminPrzegladu: addDays(14),
        notatka: 'Chciałabym umówić się na pierwszy przegląd gwarancyjny pompy ciepła.',
        ulica: 'ul. Sosnowa',
        nrDomu: '22',
        nrLokalu: null,
        kodPocztowy: '05-500',
        miejscowosc: 'Piaseczno',
        latitude: 52.0800,
        longitude: 21.0300,
      }
    ]
  },
  {
    id: 105,
    imie: 'Andrzej',
    nazwisko: 'Wójcik',
    telefon: '+48 503 777 888',
    contacted: true,
    contactedAt: subtractDays(2),
    createdAt: subtractDays(5),
    devices: [
      {
        id: 205,
        typUrzadzenia: 'Kocioł gazowy',
        nazwaUrzadzenia: 'Bosch Condens 7000i W',
        dataInstalacji: '2019-03-25',
        terminPrzegladu: subtractDays(45),
        notatka: 'Kocioł wyświetla błąd E9. Proszę o pilną wizytę serwisową.',
        ulica: 'ul. Dębowa',
        nrDomu: '5',
        nrLokalu: '10',
        kodPocztowy: '04-600',
        miejscowosc: 'Warszawa',
        latitude: 52.1700,
        longitude: 21.0800,
      }
    ]
  },
  {
    id: 106,
    imie: 'Joanna',
    nazwisko: 'Sikora',
    telefon: '+48 510 999 000',
    contacted: false,
    createdAt: subtractDays(1),
    devices: [
      {
        id: 206,
        typUrzadzenia: 'Klimatyzator',
        nazwaUrzadzenia: 'Samsung Wind-Free',
        dataInstalacji: '2024-07-15',
        terminPrzegladu: addDays(180),
        notatka: 'Nowa instalacja - proszę o pierwszy przegląd i instruktaż obsługi.',
        ulica: 'ul. Modrzewiowa',
        nrDomu: '33',
        nrLokalu: null,
        kodPocztowy: '02-800',
        miejscowosc: 'Warszawa',
        latitude: 52.1850,
        longitude: 20.9950,
      }
    ]
  }
];

// SMS History - expanded with realistic demo data
export const mockSmsHistory = [
  {
    id: 1,
    phoneNumber: '+48 500 100 200',
    clientName: 'Jan Kowalski',
    clientId: 1,
    deviceId: 1,
    deviceName: 'Viessmann Vitocal 200-S',
    deviceType: 'Pompa ciepła',
    message: 'Dzień dobry! Z tej strony firma SerwisPro. Przypominamy o zbliżającym się przeglądzie pompy ciepła Viessmann Vitocal 200-S pod adresem ul. Kwiatowa 15. Termin: ' + addDays(14) + '. Koszt serwisu 350 PLN.',
    sentAt: subtractDays(1),
    success: true,
    smsType: 'INSPECTION_REMINDER',
  },
  {
    id: 2,
    phoneNumber: '+48 501 200 300',
    clientName: 'Anna Nowak',
    clientId: 2,
    deviceId: 2,
    deviceName: 'Junkers Cerapur',
    deviceType: 'Kocioł gazowy',
    message: 'Dziękujemy za potwierdzenie terminu przeglądu kotła gazowego Junkers Cerapur. Do zobaczenia ' + addDays(7) + '. SerwisPro',
    sentAt: subtractDays(2),
    success: true,
    smsType: 'SERVICE_CONFIRMATION',
  },
  {
    id: 3,
    phoneNumber: '+48 507 800 900',
    clientName: 'Agnieszka Woźniak',
    clientId: 8,
    deviceId: 9,
    deviceName: 'Nibe F2120',
    deviceType: 'Pompa ciepła',
    message: 'Dzień dobry! Z tej strony firma SerwisPro. Przypominamy o zbliżającym się przeglądzie pompy ciepła Nibe F2120 pod adresem ul. Długa 45/2. Termin: ' + addDays(5) + '. Koszt serwisu 350 PLN.',
    sentAt: subtractDays(3),
    success: true,
    smsType: 'INSPECTION_REMINDER',
  },
  {
    id: 4,
    phoneNumber: '+48 502 300 400',
    clientName: 'Piotr Wiśniewski',
    clientId: 3,
    deviceId: 3,
    deviceName: 'Daikin FTXM35',
    deviceType: 'Klimatyzator',
    message: 'Dzień dobry! Z tej strony firma SerwisPro. Przypominamy o zbliżającym się przeglądzie klimatyzatora Daikin FTXM35 pod adresem ul. Leśna 22. Termin: ' + addDays(30) + '. Koszt serwisu 200 PLN.',
    sentAt: subtractDays(5),
    success: true,
    smsType: 'INSPECTION_REMINDER',
  },
  {
    id: 5,
    phoneNumber: '+48 503 400 500',
    clientName: 'Maria Zielińska',
    clientId: 4,
    deviceId: 5,
    deviceName: 'Vaillant ecoTEC plus',
    deviceType: 'Kocioł gazowy',
    message: 'Dzień dobry! Z tej strony firma SerwisPro. Przypominamy o zbliżającym się przeglądzie kotła gazowego Vaillant ecoTEC plus pod adresem ul. Parkowa 5. Termin: ' + addDays(21) + '. Koszt serwisu 250 PLN.',
    sentAt: subtractDays(7),
    success: true,
    smsType: 'INSPECTION_REMINDER',
  },
  {
    id: 6,
    phoneNumber: '+48 504 500 600',
    clientName: 'Tomasz Lewandowski',
    clientId: 5,
    deviceId: 6,
    deviceName: 'Panasonic Aquarea',
    deviceType: 'Pompa ciepła',
    message: 'Dzień dobry! Informujemy, że termin przeglądu Państwa pompy ciepła Panasonic Aquarea minął. Prosimy o kontakt: 123 456 789. SerwisPro',
    sentAt: subtractDays(10),
    success: true,
    smsType: 'EXPIRATION_DATE_NOTIFICATION',
  },
  {
    id: 7,
    phoneNumber: '+48 505 600 700',
    clientName: 'Katarzyna Dąbrowska',
    clientId: 6,
    deviceId: 7,
    deviceName: 'Mitsubishi MSZ-LN35',
    deviceType: 'Klimatyzator',
    message: 'Dzień dobry! Z tej strony firma SerwisPro. Przypominamy o zbliżającym się przeglądzie klimatyzatora Mitsubishi MSZ-LN35 pod adresem ul. Wiosenna 10.',
    sentAt: subtractDays(12),
    success: false,
    smsType: 'INSPECTION_REMINDER',
    errorMessage: 'Nieprawidłowy numer telefonu',
  },
  {
    id: 8,
    phoneNumber: '+48 506 700 800',
    clientName: 'Michał Szymański',
    clientId: 7,
    deviceId: 8,
    deviceName: 'Buderus Logano G125',
    deviceType: 'Kocioł olejowy',
    message: 'Dzień dobry! Z tej strony firma SerwisPro. Przypominamy o zbliżającym się przeglądzie kotła olejowego Buderus Logano G125 pod adresem ul. Cicha 7. Termin: ' + addDays(60) + '. Koszt serwisu 280 PLN.',
    sentAt: subtractDays(14),
    success: true,
    smsType: 'INSPECTION_REMINDER',
  },
  {
    id: 9,
    phoneNumber: '+48 500 100 200',
    clientName: 'Jan Kowalski',
    clientId: 1,
    deviceId: 1,
    deviceName: 'Viessmann Vitocal 200-S',
    deviceType: 'Pompa ciepła',
    message: 'Szanowny Kliencie, zapraszamy do skorzystania z promocji na przegląd pompy ciepła -15%! Oferta ważna do końca miesiąca. SerwisPro',
    sentAt: subtractDays(15),
    success: true,
    smsType: 'ADVERTISING',
  },
  {
    id: 10,
    phoneNumber: '+48 501 200 300',
    clientName: 'Anna Nowak',
    clientId: 2,
    deviceId: 2,
    deviceName: 'Junkers Cerapur',
    deviceType: 'Kocioł gazowy',
    message: 'Dzień dobry! Z tej strony firma SerwisPro. Przypominamy o zbliżającym się przeglądzie kotła gazowego Junkers Cerapur.',
    sentAt: subtractDays(18),
    success: true,
    smsType: 'MANUAL_INSPECTION_REMINDER',
  },
  {
    id: 11,
    phoneNumber: '+48 512 345 678',
    clientName: 'Robert Malinowski',
    clientId: 101,
    deviceId: 201,
    deviceName: 'Viessmann Vitocal 300-G',
    deviceType: 'Pompa ciepła',
    message: 'Dzień dobry! Otrzymaliśmy Państwa zgłoszenie serwisowe. Skontaktujemy się w ciągu 24h. SerwisPro',
    sentAt: subtractDays(1),
    success: true,
    smsType: 'GENERAL_NOTIFICATION',
  },
  {
    id: 12,
    phoneNumber: '+48 601 234 567',
    clientName: 'Ewa Pawlak',
    clientId: 102,
    deviceId: 202,
    deviceName: 'Viessmann Vitodens 200-W',
    deviceType: 'Kocioł gazowy',
    message: 'Dzień dobry! Informujemy, że termin przeglądu Państwa kotła gazowego minął. Prosimy o kontakt w celu umówienia wizyty.',
    sentAt: subtractDays(4),
    success: true,
    smsType: 'MANUAL_EXPIRATION_NOTIFICATION',
  },
  {
    id: 13,
    phoneNumber: '+48 789 012 345',
    clientName: 'Krzysztof Nowicki',
    clientId: 103,
    deviceId: 203,
    deviceName: 'LG Artcool Gallery',
    deviceType: 'Klimatyzator',
    message: 'Dziękujemy za skorzystanie z usług SerwisPro. Prosimy o opinię na temat wykonanej usługi.',
    sentAt: subtractDays(6),
    success: true,
    smsType: 'CUSTOM',
  },
  {
    id: 14,
    phoneNumber: '+48 660 111 222',
    clientName: 'Magdalena Kaczmarek',
    clientId: 104,
    deviceId: 204,
    deviceName: 'Mitsubishi Ecodan',
    deviceType: 'Pompa ciepła',
    message: 'Dzień dobry! Z tej strony firma SerwisPro. Przypominamy o zbliżającym się przeglądzie pompy ciepła Mitsubishi Ecodan.',
    sentAt: subtractDays(8),
    success: false,
    smsType: 'INSPECTION_REMINDER',
    errorMessage: 'Numer tymczasowo niedostępny',
  },
  {
    id: 15,
    phoneNumber: '+48 503 777 888',
    clientName: 'Andrzej Wójcik',
    clientId: 105,
    deviceId: 205,
    deviceName: 'Bosch Condens 7000i W',
    deviceType: 'Kocioł gazowy',
    message: 'Dzień dobry! Potwierdzamy umówioną wizytę serwisową na ' + subtractDays(-2) + ' o godzinie 10:00. SerwisPro',
    sentAt: subtractDays(3),
    success: true,
    smsType: 'SERVICE_CONFIRMATION',
  },
  {
    id: 16,
    phoneNumber: '+48 510 999 000',
    clientName: 'Joanna Sikora',
    clientId: 106,
    deviceId: 206,
    deviceName: 'Samsung Wind-Free',
    deviceType: 'Klimatyzator',
    message: 'Witamy w gronie klientów SerwisPro! Dziękujemy za zaufanie. W razie pytań prosimy o kontakt: 123 456 789.',
    sentAt: subtractDays(1),
    success: true,
    smsType: 'GENERAL_NOTIFICATION',
  },
  {
    id: 17,
    phoneNumber: '+48 502 300 400',
    clientName: 'Piotr Wiśniewski',
    clientId: 3,
    deviceId: 4,
    deviceName: 'Bosch Compress 7000i',
    deviceType: 'Pompa ciepła',
    message: 'Dzień dobry! Informujemy, że termin przeglądu Państwa pompy ciepła Bosch Compress 7000i minął ' + subtractDays(3) + '. Prosimy o pilny kontakt.',
    sentAt: subtractDays(2),
    success: true,
    smsType: 'EXPIRATION_DATE_NOTIFICATION',
  },
  {
    id: 18,
    phoneNumber: '+48 507 800 900',
    clientName: 'Agnieszka Woźniak',
    clientId: 8,
    deviceId: 9,
    deviceName: 'Nibe F2120',
    deviceType: 'Pompa ciepła',
    message: 'Dziękujemy za potwierdzenie terminu przeglądu. Nasz technik przyjedzie ' + addDays(5) + ' między 14:00 a 16:00. SerwisPro',
    sentAt: subtractDays(2),
    success: true,
    smsType: 'SERVICE_CONFIRMATION',
  },
  {
    id: 19,
    phoneNumber: '+48 500 100 200',
    clientName: 'Jan Kowalski',
    clientId: 1,
    deviceId: 1,
    deviceName: 'Viessmann Vitocal 200-S',
    deviceType: 'Pompa ciepła',
    message: 'Przegląd pompy ciepła został wykonany pomyślnie. Dziękujemy za skorzystanie z usług SerwisPro!',
    sentAt: subtractDays(30),
    success: true,
    smsType: 'CUSTOM',
  },
  {
    id: 20,
    phoneNumber: '+48 501 200 300',
    clientName: 'Anna Nowak',
    clientId: 2,
    deviceId: 2,
    deviceName: 'Junkers Cerapur',
    deviceType: 'Kocioł gazowy',
    message: 'Dzień dobry! Zapraszamy na sezonowy przegląd kotła gazowego przed sezonem grzewczym. Promocyjna cena: 220 PLN. SerwisPro',
    sentAt: subtractDays(45),
    success: true,
    smsType: 'ADVERTISING',
  },
  {
    id: 21,
    phoneNumber: '+48 503 400 500',
    clientName: 'Maria Zielińska',
    clientId: 4,
    deviceId: 5,
    deviceName: 'Vaillant ecoTEC plus',
    deviceType: 'Kocioł gazowy',
    message: 'Przypomnienie: Jutro o 9:00 wizyta serwisowa. Prosimy o zapewnienie dostępu do kotła. SerwisPro',
    sentAt: subtractDays(22),
    success: true,
    smsType: 'MANUAL_CUSTOM',
  },
  {
    id: 22,
    phoneNumber: '+48 504 500 600',
    clientName: 'Tomasz Lewandowski',
    clientId: 5,
    deviceId: 6,
    deviceName: 'Panasonic Aquarea',
    deviceType: 'Pompa ciepła',
    message: 'Dzień dobry! Z tej strony firma SerwisPro. Przypominamy o zbliżającym się przeglądzie pompy ciepła.',
    sentAt: subtractDays(25),
    success: false,
    smsType: 'INSPECTION_REMINDER',
    errorMessage: 'Brak środków na koncie SMS',
  },
  {
    id: 23,
    phoneNumber: '+48 506 700 800',
    clientName: 'Michał Szymański',
    clientId: 7,
    deviceId: 8,
    deviceName: 'Buderus Logano G125',
    deviceType: 'Kocioł olejowy',
    message: 'Serwis kotła olejowego zakończony. Wymieniono filtr oleju i uszczelki. Koszt: 380 PLN. Dziękujemy! SerwisPro',
    sentAt: subtractDays(60),
    success: true,
    smsType: 'CUSTOM',
  },
  {
    id: 24,
    phoneNumber: '+48 505 600 700',
    clientName: 'Katarzyna Dąbrowska',
    clientId: 6,
    deviceId: 7,
    deviceName: 'Mitsubishi MSZ-LN35',
    deviceType: 'Klimatyzator',
    message: 'Informujemy o zmianie terminu przeglądu klimatyzatora na ' + addDays(3) + '. Przepraszamy za utrudnienia. SerwisPro',
    sentAt: subtractDays(15),
    success: true,
    smsType: 'GENERAL_NOTIFICATION',
  },
  {
    id: 25,
    phoneNumber: '+48 512 345 678',
    clientName: 'Robert Malinowski',
    clientId: 101,
    deviceId: 201,
    deviceName: 'Viessmann Vitocal 300-G',
    deviceType: 'Pompa ciepła',
    message: 'Dzień dobry! Nasz technik potwierdził wizytę na ' + subtractDays(-1) + ' o 11:00. W razie zmian prosimy o kontakt.',
    sentAt: subtractDays(2),
    success: true,
    smsType: 'SERVICE_CONFIRMATION',
  },
];

// Planned SMS - expanded with realistic demo data
export const mockPlannedSms = [
  {
    id: 1,
    phoneNumber: '+48 500 100 200',
    message: 'Dzień dobry! Z tej strony firma SerwisPro. Przypominamy o zbliżającym się przeglądzie pompy ciepła Viessmann Vitocal 200-S. Termin: ' + addDays(1) + '. Koszt serwisu 350 PLN.',
    scheduledAt: addDays(1),
    createdAt: subtractDays(7),
    status: 'SCHEDULED',
    smsType: 'INSPECTION_REMINDER',
    plannedSource: 'AUTOMATIC_SCHEDULER',
    device: { id: 1, nazwaUrzadzenia: 'Viessmann Vitocal 200-S', typUrzadzenia: { displayName: 'Pompa ciepła' } },
    client: { id: 1, imie: 'Jan', nazwisko: 'Kowalski' },
  },
  {
    id: 2,
    phoneNumber: '+48 501 200 300',
    message: 'Dzień dobry! Z tej strony firma SerwisPro. Przypominamy o zbliżającym się przeglądzie kotła gazowego Junkers Cerapur. Termin: ' + addDays(2) + '. Koszt serwisu 250 PLN.',
    scheduledAt: addDays(2),
    createdAt: subtractDays(5),
    status: 'SCHEDULED',
    smsType: 'INSPECTION_REMINDER',
    plannedSource: 'AUTOMATIC_SCHEDULER',
    device: { id: 2, nazwaUrzadzenia: 'Junkers Cerapur', typUrzadzenia: { displayName: 'Kocioł gazowy' } },
    client: { id: 2, imie: 'Anna', nazwisko: 'Nowak' },
  },
  {
    id: 3,
    phoneNumber: '+48 502 300 400',
    message: 'Dzień dobry! Z tej strony firma SerwisPro. Przypominamy o zbliżającym się przeglądzie klimatyzatora Daikin FTXM35. Termin: ' + addDays(3) + '. Koszt serwisu 200 PLN.',
    scheduledAt: addDays(3),
    createdAt: subtractDays(4),
    status: 'SCHEDULED',
    smsType: 'INSPECTION_REMINDER',
    plannedSource: 'AUTOMATIC_SCHEDULER',
    device: { id: 3, nazwaUrzadzenia: 'Daikin FTXM35', typUrzadzenia: { displayName: 'Klimatyzator' } },
    client: { id: 3, imie: 'Piotr', nazwisko: 'Wiśniewski' },
  },
  {
    id: 4,
    phoneNumber: '+48 503 400 500',
    message: 'Dzień dobry! Z tej strony firma SerwisPro. Przypominamy o zbliżającym się przeglądzie kotła gazowego Vaillant ecoTEC plus. Termin: ' + addDays(5) + '. Koszt serwisu 250 PLN.',
    scheduledAt: addDays(5),
    createdAt: subtractDays(3),
    status: 'SCHEDULED',
    smsType: 'INSPECTION_REMINDER',
    plannedSource: 'AUTOMATIC_SCHEDULER',
    device: { id: 5, nazwaUrzadzenia: 'Vaillant ecoTEC plus', typUrzadzenia: { displayName: 'Kocioł gazowy' } },
    client: { id: 4, imie: 'Maria', nazwisko: 'Zielińska' },
  },
  {
    id: 5,
    phoneNumber: '+48 504 500 600',
    message: 'Dzień dobry! Informujemy, że termin przeglądu Państwa pompy ciepła Panasonic Aquarea mija ' + addDays(7) + '. Prosimy o kontakt.',
    scheduledAt: addDays(7),
    createdAt: subtractDays(2),
    status: 'SCHEDULED',
    smsType: 'EXPIRATION_DATE_NOTIFICATION',
    plannedSource: 'AUTOMATIC_SCHEDULER',
    device: { id: 6, nazwaUrzadzenia: 'Panasonic Aquarea', typUrzadzenia: { displayName: 'Pompa ciepła' } },
    client: { id: 5, imie: 'Tomasz', nazwisko: 'Lewandowski' },
  },
  {
    id: 6,
    phoneNumber: '+48 505 600 700',
    message: 'Dzień dobry! Z tej strony firma SerwisPro. Przypominamy o zbliżającym się przeglądzie klimatyzatora Mitsubishi MSZ-LN35. Termin: ' + addDays(10) + '.',
    scheduledAt: addDays(10),
    createdAt: subtractDays(1),
    status: 'SCHEDULED',
    smsType: 'INSPECTION_REMINDER',
    plannedSource: 'AUTOMATIC_SCHEDULER',
    device: { id: 7, nazwaUrzadzenia: 'Mitsubishi MSZ-LN35', typUrzadzenia: { displayName: 'Klimatyzator' } },
    client: { id: 6, imie: 'Katarzyna', nazwisko: 'Dąbrowska' },
  },
  {
    id: 7,
    phoneNumber: '+48 506 700 800',
    message: 'Dzień dobry! Z tej strony firma SerwisPro. Przypominamy o zbliżającym się przeglądzie kotła olejowego Buderus Logano G125. Termin: ' + addDays(14) + '. Koszt serwisu 280 PLN.',
    scheduledAt: addDays(14),
    createdAt: subtractDays(1),
    status: 'SCHEDULED',
    smsType: 'INSPECTION_REMINDER',
    plannedSource: 'AUTOMATIC_SCHEDULER',
    device: { id: 8, nazwaUrzadzenia: 'Buderus Logano G125', typUrzadzenia: { displayName: 'Kocioł olejowy' } },
    client: { id: 7, imie: 'Michał', nazwisko: 'Szymański' },
  },
  {
    id: 8,
    phoneNumber: '+48 507 800 900',
    message: 'Dzień dobry! Z tej strony firma SerwisPro. Przypominamy o zbliżającym się przeglądzie pompy ciepła Nibe F2120. Termin: ' + addDays(21) + '. Koszt serwisu 350 PLN.',
    scheduledAt: addDays(21),
    createdAt: new Date().toISOString(),
    status: 'SCHEDULED',
    smsType: 'INSPECTION_REMINDER',
    plannedSource: 'AUTOMATIC_SCHEDULER',
    device: { id: 9, nazwaUrzadzenia: 'Nibe F2120', typUrzadzenia: { displayName: 'Pompa ciepła' } },
    client: { id: 8, imie: 'Agnieszka', nazwisko: 'Woźniak' },
  },
  {
    id: 9,
    phoneNumber: '+48 512 345 678',
    message: 'Dzień dobry! Z tej strony firma SerwisPro. Przypominamy o zbliżającym się przeglądzie pompy ciepła Viessmann Vitocal 300-G. Termin: ' + addDays(28) + '.',
    scheduledAt: addDays(28),
    createdAt: new Date().toISOString(),
    status: 'SCHEDULED',
    smsType: 'INSPECTION_REMINDER',
    plannedSource: 'MANUAL_USER',
    device: { id: 201, nazwaUrzadzenia: 'Viessmann Vitocal 300-G', typUrzadzenia: { displayName: 'Pompa ciepła' } },
    client: { id: 101, imie: 'Robert', nazwisko: 'Malinowski' },
  },
  {
    id: 10,
    phoneNumber: '+48 601 234 567',
    message: 'Szanowni Państwo! Zapraszamy do skorzystania z promocji na przegląd urządzenia grzewczego -15%! Oferta ważna do końca miesiąca. SerwisPro',
    scheduledAt: addDays(3),
    createdAt: new Date().toISOString(),
    status: 'SCHEDULED',
    smsType: 'ADVERTISING',
    plannedSource: 'MANUAL_USER',
    device: null,
    client: { id: 102, imie: 'Ewa', nazwisko: 'Pawlak' },
  },
  {
    id: 11,
    phoneNumber: '+48 500 100 200',
    message: 'Dzień dobry! Z tej strony firma SerwisPro. Przypominamy o przeglądzie pompy ciepła.',
    scheduledAt: subtractDays(5),
    createdAt: subtractDays(12),
    sentAt: subtractDays(5),
    status: 'SENT',
    smsType: 'INSPECTION_REMINDER',
    plannedSource: 'AUTOMATIC_SCHEDULER',
    device: { id: 1, nazwaUrzadzenia: 'Viessmann Vitocal 200-S', typUrzadzenia: { displayName: 'Pompa ciepła' } },
    client: { id: 1, imie: 'Jan', nazwisko: 'Kowalski' },
  },
  {
    id: 12,
    phoneNumber: '+48 501 200 300',
    message: 'Dzień dobry! Z tej strony firma SerwisPro. Przypominamy o przeglądzie kotła gazowego.',
    scheduledAt: subtractDays(10),
    createdAt: subtractDays(17),
    sentAt: subtractDays(10),
    status: 'SENT',
    smsType: 'INSPECTION_REMINDER',
    plannedSource: 'AUTOMATIC_SCHEDULER',
    device: { id: 2, nazwaUrzadzenia: 'Junkers Cerapur', typUrzadzenia: { displayName: 'Kocioł gazowy' } },
    client: { id: 2, imie: 'Anna', nazwisko: 'Nowak' },
  },
  {
    id: 13,
    phoneNumber: '+48 660 111 222',
    message: 'Dzień dobry! Z tej strony firma SerwisPro. Przypominamy o przeglądzie pompy ciepła Mitsubishi Ecodan.',
    scheduledAt: subtractDays(3),
    createdAt: subtractDays(10),
    status: 'FAILED',
    smsType: 'INSPECTION_REMINDER',
    plannedSource: 'AUTOMATIC_SCHEDULER',
    errorMessage: 'Nieprawidłowy numer telefonu',
    device: { id: 204, nazwaUrzadzenia: 'Mitsubishi Ecodan', typUrzadzenia: { displayName: 'Pompa ciepła' } },
    client: { id: 104, imie: 'Magdalena', nazwisko: 'Kaczmarek' },
  },
  {
    id: 14,
    phoneNumber: '+48 503 400 500',
    message: 'Dzień dobry! Z tej strony firma SerwisPro. Przypominamy o przeglądzie kotła gazowego.',
    scheduledAt: subtractDays(15),
    createdAt: subtractDays(22),
    status: 'CANCELLED',
    smsType: 'INSPECTION_REMINDER',
    plannedSource: 'AUTOMATIC_SCHEDULER',
    device: { id: 5, nazwaUrzadzenia: 'Vaillant ecoTEC plus', typUrzadzenia: { displayName: 'Kocioł gazowy' } },
    client: { id: 4, imie: 'Maria', nazwisko: 'Zielińska' },
  },
  {
    id: 15,
    phoneNumber: '+48 789 012 345',
    message: 'Szanowni Państwo! Zapraszamy do skorzystania z promocji sezonowej. SerwisPro',
    scheduledAt: subtractDays(20),
    createdAt: subtractDays(25),
    sentAt: subtractDays(20),
    status: 'SENT',
    smsType: 'ADVERTISING',
    plannedSource: 'MANUAL_USER',
    device: null,
    client: { id: 103, imie: 'Krzysztof', nazwisko: 'Nowicki' },
  },
  {
    id: 16,
    phoneNumber: '+48 510 999 000',
    message: 'Dzień dobry! Informujemy, że termin przeglądu Państwa klimatyzatora Samsung Wind-Free mija ' + addDays(45) + '.',
    scheduledAt: addDays(45),
    createdAt: new Date().toISOString(),
    status: 'SCHEDULED',
    smsType: 'EXPIRATION_DATE_NOTIFICATION',
    plannedSource: 'AUTOMATIC_SCHEDULER',
    device: { id: 206, nazwaUrzadzenia: 'Samsung Wind-Free', typUrzadzenia: { displayName: 'Klimatyzator' } },
    client: { id: 106, imie: 'Joanna', nazwisko: 'Sikora' },
  },
  {
    id: 17,
    phoneNumber: '+48 503 777 888',
    message: 'Dzień dobry! Z tej strony firma SerwisPro. Przypominamy o zbliżającym się przeglądzie kotła gazowego Bosch Condens 7000i W. Termin: ' + addDays(60) + '.',
    scheduledAt: addDays(60),
    createdAt: new Date().toISOString(),
    status: 'SCHEDULED',
    smsType: 'INSPECTION_REMINDER',
    plannedSource: 'AUTOMATIC_SCHEDULER',
    device: { id: 205, nazwaUrzadzenia: 'Bosch Condens 7000i W', typUrzadzenia: { displayName: 'Kocioł gazowy' } },
    client: { id: 105, imie: 'Andrzej', nazwisko: 'Wójcik' },
  },
  {
    id: 18,
    phoneNumber: '+48 502 300 400',
    message: 'Dzień dobry! Z tej strony firma SerwisPro. Przypominamy o zbliżającym się przeglądzie pompy ciepła Bosch Compress 7000i. Termin: ' + addDays(90) + '.',
    scheduledAt: addDays(90),
    createdAt: new Date().toISOString(),
    status: 'SCHEDULED',
    smsType: 'INSPECTION_REMINDER',
    plannedSource: 'AUTOMATIC_SCHEDULER',
    device: { id: 4, nazwaUrzadzenia: 'Bosch Compress 7000i', typUrzadzenia: { displayName: 'Pompa ciepła' } },
    client: { id: 3, imie: 'Piotr', nazwisko: 'Wiśniewski' },
  },
];

// Settings
export const mockSettings = {
  smsTemplates: {
    reminder: 'Szanowny Kliencie, przypominamy o nadchodzącym przeglądzie Państwa urządzenia {deviceType}. Termin: {inspectionDate}. Prosimy o potwierdzenie: {confirmationLink}. SerwisPro',
    expiration: 'Informujemy, że termin przeglądu Państwa urządzenia {deviceType} minął. Prosimy o kontakt: {contactPhoneNumber}. SerwisPro',
    confirmation: 'Dziękujemy za potwierdzenie terminu przeglądu. Do zobaczenia {inspectionDate}. SerwisPro',
    cancellation: 'Państwa wizita serwisowa została anulowana. W razie pytań prosimy o kontakt.',
    expirationDayEnabled: true,
  },
  pricing: {
    heatPump: 350,
    gasBoiler: 250,
    oilBoiler: 280,
    airConditioner: 200,
    other: 220
  },
  inspectionIntervals: {
    heatPump: 12,
    gasBoiler: 12,
    oilBoiler: 12,
    airConditioner: 6,
    other: 12
  },
  companyInfo: {
    name: 'SerwisPro',
    phone: '123 456 789',
    email: 'kontakt@serwispro.pl',
    address: 'ul. Serwisowa 15, 00-100 Warszawa'
  },
  smsSettings: {
    reminderDaysAhead: 30,
    automaticSmsEnabled: true,
    contactPhoneNumber: '123 456 789'
  }
};

// Demo user
export const mockUser = {
  id: 1,
  username: 'demo',
  email: 'demo@serwispro.pl',
  firstName: 'Demo',
  lastName: 'User',
  role: 'ADMIN',
  roles: ['ADMIN', 'ROLE_USER'],
};

// Service history for devices
export const mockServiceHistory = {
  1: [ // Device ID 1
    {
      id: 101,
      deviceId: 1,
      serviceDate: subtractDays(365),
      serviceType: 'Przegląd okresowy',
      notes: 'Przegląd roczny - wszystko w porządku',
      price: 350,
      technician: 'Jan Technik',
    }
  ],
  2: [ // Device ID 2
    {
      id: 102,
      deviceId: 2,
      serviceDate: subtractDays(180),
      serviceType: 'Przegląd okresowy',
      notes: 'Wymiana uszczelek, czyszczenie',
      price: 250,
      technician: 'Jan Technik',
    },
    {
      id: 103,
      deviceId: 2,
      serviceDate: subtractDays(545),
      serviceType: 'Instalacja',
      notes: 'Instalacja nowego kotła',
      price: 500,
      technician: 'Piotr Instalator',
    }
  ],
  9: [ // Device ID 9
    {
      id: 104,
      deviceId: 9,
      serviceDate: subtractDays(365),
      serviceType: 'Przegląd okresowy',
      notes: 'Przegląd roczny, uzupełnienie czynnika',
      price: 350,
      technician: 'Jan Technik',
    }
  ]
};

// Reports data
export const mockReportsData = {
  totalClients: mockClients.length,
  totalDevices: mockDevices.length,
  totalServices: mockServices.length,
  servicesThisMonth: 12,
  revenue: {
    thisMonth: 4850,
    lastMonth: 5200,
    thisYear: 52400
  },
  devicesByType: {
    'Pompa ciepła': 4,
    'Kocioł gazowy': 2,
    'Klimatyzator': 2,
    'Kocioł olejowy': 1
  },
  monthlyServices: [
    { monthName: 'Styczeń', totalServices: 8, revenue: 2800, completedServices: 7 },
    { monthName: 'Luty', totalServices: 6, revenue: 2100, completedServices: 6 },
    { monthName: 'Marzec', totalServices: 10, revenue: 3500, completedServices: 9 },
    { monthName: 'Kwiecień', totalServices: 14, revenue: 4900, completedServices: 13 },
    { monthName: 'Maj', totalServices: 11, revenue: 3850, completedServices: 10 },
    { monthName: 'Czerwiec', totalServices: 9, revenue: 3150, completedServices: 8 },
    { monthName: 'Lipiec', totalServices: 7, revenue: 2450, completedServices: 7 },
    { monthName: 'Sierpień', totalServices: 6, revenue: 2100, completedServices: 5 },
    { monthName: 'Wrzesień', totalServices: 13, revenue: 4550, completedServices: 12 },
    { monthName: 'Październik', totalServices: 16, revenue: 5600, completedServices: 15 },
    { monthName: 'Listopad', totalServices: 12, revenue: 4200, completedServices: 11 },
    { monthName: 'Grudzień', totalServices: 9, revenue: 3150, completedServices: 8 }
  ],
  smsStats: {
    totalSent: 156,
    delivered: 148,
    failed: 3,
    pending: 5,
    successRate: 98.0,
    remindersSent: 124,
    confirmationsSent: 32,
    estimatedCost: 23.40
  }
};
